import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import RootProvider from '@/src/providers/root-provider';
import { ThemeProvider } from '@/src/providers/theme-provider';
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Prime Care Admin Dashboard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable}  antialiased flex`}>
        <RootProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <main className="w-full min-h-screen">
                <div className="">{children}</div>
              </main>
            <Toaster />
          </ThemeProvider>
        </RootProvider>
      </body>
    </html>
  );
}
